### ISSUE TITLE
Can't load xray.xobsolete

### ISSUE THREAD

**Issue by justincely** [spacetelescope/pyraf#19]
Trying to load this subpackage throws an IRAF error on my OSX and Linux boxes:
`IrafError: Cannot find executable for task xobsolete`

The [online doc](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?xray.hlp) for the xray package seems to indicate that this package is a good candidate for removal, as it will "soon be removed from the system."

**Comment by pllim** [comment]
According to http://iraf.noao.edu/faq/FAQsec04.html , XRAY package is Harvard's, not ours.
```
    XRAY - the SAO Post-Reduction Off-line Software (PROS) package for analysis
        of reduced X-ray data.  The PROS software includes spatial, spectral,
        timing, data I/O and conversion routines, plotting applications and
        general algorithms for performing arithmetic operations with imaging
	data.  Available from sao-ftp.harvard.edu in the pub/pros directory.
```
