### ISSUE TITLE
Problem loading noao.obsutil.kpno task

### ISSUE THREAD

**Issue by justincely** [spacetelescope/pyraf#22]
This one hits a strange error when you try to load it.

```
--> kpno
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
  File "<CL script obsutil.kpno>", line 18, in kpno
    if (iraf.access('spectimedb$')):
IrafError: Undefined variable `spectimedb' in string `spectimedb$'
```

**Comment by sosey** [comment]
this sounds like an environment variable issue, spectimedb isn't set in your login.cl.  In an iraf term set it to something and see if kpno loads:

set spectimedb='/grp/cdbs/'  

or anything else just to test it.

**Comment by pllim** [comment]
[KPNO](https://www.noao.edu/kpno/) is also not ours.
