### ISSUE TITLE
Can't load stsdas.sobsolete

### ISSUE THREAD

**Issue by justincely** [spacetelescope/pyraf#23]
Can't find the executable:

```
--> sobsolete
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
IrafError: Cannot find executable for task sobsolete
```

**Comment by pllim** [comment]
Okay, this might be ours (http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?sobsolete.men). But perhaps it is not a bad thing preventing people from using obsolete stuff...

**Comment by pllim** [comment]
I am just going to close this for now. If someone really wants to use `sobsolete`, we can reopen.
