### ISSUE TITLE
kelper package still importing pyfits

### ISSUE THREAD

**Issue by justincely** [spacetelescope/pyraf#24]
trying to load the kepler package hits an error as it's trying to load pyfits

```
--> kepler
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
    iraf.kepler(_save=1)
  File "<CL script clpackage.kepler>", line 33, in kepler
    iraf.pyexecute('kepler$kepbls.py', verbose = no, PkgName=PkgName,PkgBinary=PkgBinary)
  File "/Users/ely/anaconda/envs/iraf/variants/common//iraf/kepler/kepbls.py", line 1, in <module>
    import numpy, scipy, sys, time, pyfits, pylab, math, re
ImportError: No module named pyfits
```

**Comment by pllim** [comment]
How is this our problem? Shouldn't this be reported to Kepler Help Desk?

**Comment by jhunkeler** [comment]
@pllim Indeed

**Comment by sosey** [comment]
I thought @philhodge worked on the kepler software?

**Comment by pllim** [comment]
Are we talking about the same Kepler? https://keplerscience.arc.nasa.gov/software.html

**Comment by sosey** [comment]
Is this stuff in pyraf the kepler/k2  stuff? I thought it was the original mission stuff.

**Comment by sosey** [comment]
one vehicle, the original mission ended when they lost a reaction wheel, they regrouped and K2 started

**Comment by philhodge** [comment]
Dave and I worked on Kepler for a while, but the IDT wanted to use their code.

I don't know what the iraf/pyraf kepler package contains.  Not our stuff, though.

**Comment by pllim** [comment]
>  Not our stuff, though.

Good! Closing.
