### ISSUE TITLE
Can't load xray.xlocal

### ISSUE THREAD

**Issue by justincely** [spacetelescope/pyraf#25]
More missing executables

```
--> xlocal
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
IrafError: Cannot find executable for task xlocal
```

**Comment by cdsontag** [comment]
Love to see all this interest in PyRAF, but I'm curious - who is it that you imagine is going to get to fixing all these tickets being filed?

**Comment by justincely** [comment]
Just logging the issues for knowledge's sake at the moment, so we don't have to do rediscovery in the future.  If some are easy to fix, that would be nice, but If nothing else we can close these as "not interested in fixing" after we've had the discussion.

Additionally SSB does have some resources to work on transitioning off of any dependency on IRAF, and part of this will take the form of finding replacement workflows or writing new python equivalents to existing tasks.  Each task that doesn't work/hasn't worked for some time has a strong argument for NOT replacing, so it's good to know which are broken.

**Comment by cdsontag** [comment]
OK.  It would be great to see some other SSB folks getting involved in these fixes if needed.

**Comment by justincely** [comment]
Absolutely - not putting all this on your shoulders by filing the issues!  Just logging what I found for the moment, we'll see about what even should be fixed first, and then see about who can do it as we get time.

Feel free to log any thoughts you have on any of the open tickets, if something seems clear or you know a good starting point to look, may help in the future if we come back to them.

**Comment by pllim** [comment]
Not ours. See https://github.com/spacetelescope/pyraf/issues/19#issuecomment-377431641
