### ISSUE TITLE
Failed tests: Corrupted or truncated file

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pyraf#34]
Appeared today on pembry dev:
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=26398
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=26259

c/c @cdsontag , @jhunkeler

**Comment by cdsontag** [comment]
I'm willing to give it a day and see if it repeats
