### ISSUE TITLE
pyraf in mybinder

### ISSUE THREAD

**Issue by iskreng** [spacetelescope/pyraf#62]
Hello,

I was trying to create a quick notebook on processing some data that I could share with a colleague online via mybinder.org. However, I encountered the issue that pyraf wouldn't recognize the iraf installation. It comes down to setting the environment variables iraf and irafarch. I have opened this issue yesterday on the mybinder github site, where you can check the brief discussion we had:
https://github.com/jupyterhub/binderhub/issues/575
They recommended that I get in touch with you to resolve this issue. The main suggestion was to use the os python module to set the environment variables at the first cell. I did that and unfortunately they still weren't set. I would appreciate if you have any thoughts/suggestions?

Many thanks,
Iskren

**Comment by SaOgaz** [comment]
Hi @iskreng,

Unfortunately we have very few resources to help with current Pyraf support issues, particularly when it comes to getting Pyraf to work with new software.  We are currently working on phasing out Pyraf completely and will be dropping all support for it in the future (still working out the full public announcement for this).  We do have some resources that can help you find some Python replacements for many IRAF tasks here: http://stak-notebooks.readthedocs.io/en/latest/.

**Comment by SaOgaz** [comment]
Closing this call for now.  @iskreng feel free to post here if you have further questions.
